# Generated by Django 2.1.3 on 2019-05-10 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='expire',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='licence',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='licence_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
