# Generated by Django 2.1.2 on 2018-10-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20181022_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='likes',
        ),
    ]
