# Generated by Django 2.1.2 on 2018-10-22 15:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20181022_1514'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together={('user', 'quiz')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'quiz')},
        ),
    ]
