# Generated by Django 2.1.2 on 2018-10-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20181023_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
