# Generated by Django 2.1.3 on 2019-02-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20181029_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='uniq_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
